TARGET = Tutorial


PSPSDK=$(shell psp-config --pspsdk-path)

OBJS = main.o

INCDIR = ../include
CFLAGS = -G0 -Wall -O2 -g3
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR = ../../lib
LDFLAGS = 
LIBS= -lpspkernel


EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Tutorial1
PSP_FW_VERSION=500
BUILD_PRX = 1
PSP_LARGE_MEMORY = 0


include $(PSPSDK)/lib/build.mak