TARGET = Tutorial

OBJS = main.o

INCDIR = ../include
CFLAGS = -G0 -Wall -O2
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS = 
LIBS= 


EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Tutorial1
PSP_FW_VERSION=500
PSP_LARGE_MEMORY = 1

include ${PSPSDK_CLANG}/psp/SDK/lib/build.mak